dist: bionic
os: linux
language: python
python:
  - "3.7"

cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio check
  - platformio run

notifications:
  slack:
    rooms:
      secure: UQSmhwOtsP5jXnQX5khSqwNRt+p9X+xKfkoyz3f5jRNFipXn7gMEIqyfCZOt9cFNaya9IsUbQRb7bJOUU3GrAutwtlWqoGP5AxDlKKZnve3DsWbtzyGE9tzuHr9mlj95spzYviHP4v/BkppraiSDt6494YuhfXHQJ7+S79lJTVnIZnLNLrtf3xdWg+79HGzFcbRPp7hscgxYdIEXQZaQS0RfMDLbr8out4hbF355Yvtq+pko/81Xh/VEhyfuyilr9wHrN0cOMpboiJEuVtPtsQtXN/UzsZrImMHWuErV7WSckWSMbd9PkS7O9HwvCcUrQc0JeDymoeoMtk7UFX5hHpPFNZultxHehisHM0tPw4bquvK+KWR7bLL210ldqhwvCZkOp25A1rPuwOgm6C815U/GOo0sK08vDr2b0VqyGpZJwgABahXMeXwoF1mihGDdHtjbXWg6/WYrQfpHZIyHhOjcWoclrpwE0gF1Tr61SQCJaQlaELfDnwjIWxY/PBkk8ZRhRZUKKBraXlaHkF/D46qcX12F7q73Bu/g8w/bjZh/WCIjrg0y61HgKWKld1LZHrOih/mc2UZKrBT9dRGtyOkkuHNx2kKB7SvEjPh/bJBJNqrjxm/JyNn1vS/joqA84XT82RwVXKuVlntzGV/yvXyYkCVkLrAymcnFm+yhjP8=
