dist: bionic
language: python
python:
  - "3.7"

cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio check
  - platformio run

notifications:
  slack:
    rooms:
      secure: RLwrXoQoYeiDTDOh9dPRdsw78lhhn4B8aiv70xZprQKlSgOrlw18+rkwV+M9LAVBCOIaucQWRUBQiaSWRtagmw/E1s55R51SPkm9wRqjwJpdQ3pJiqKxxlEB/iTL5x67HAfbQ1ayP7CzhbDyu1dw9X11DMBNi+KzmtZt5ONNflZmEE+dChp7ipNCHES+seJl1BmYg6v/OHCB4JnqGZoPEg33ITu713bt5NicA0y7wNd3NadGKFcOXONHAMnmzrcnT0LLV11wF1Z49yn4ig2orEN/4cpn3bstky6dKUD1cz3mv3W4CSC7KLuzDUz9lQBb8kv9Q3TIJMgI9Hnb2JamuS709JmKAEeh4B49Sf5lYgemiK1UevYS37F7ee7bXHSF5IO0DZxin6L0yY6dLWleO6zT/uKu1LHMY8+XAE+DKX/Tzh8W2WXhda5BOfxoKeplrEUTaeSD71dtYQq0kvRpBgexaMwWRQ/Ef5Gk4ts7HmxI12rU/PDJl01KtW5p4gTgorDg5gybvt5eMvYYUQMSdni4oBOxJe1j2V0n5e7+GVUTcBdW3BpPotkh78oSjs9eO17g6a4Pg8itqSz2wbeyYFNAlP1mN1oDiKFUXPpklDgdLHMap2nVlNG2ha/E8lBtq6mysn5/dLScOSuq7UBxJFXxJO2F6dr4fMRT51a+hv4=
